const productTypes = {
    FETCH_PRODUCT: 'FETCH_PRODUCT',
    FETCH_PRODUCT_SEARCH:'FETCH_PRODUCT_SEARCH',
    FETCH_PRODUCT_ERR: 'FETCH_PRODUCT_ERR',
    SET_CATEGORY:'SET_CATEGORY',
    SET_CATEGORY_ERR:'SET_CATEGORY_ERR',
    SET_PRODUCT_DETAIL:'SET_PRODUCT_DETAIL',


    ADDPRODUCTS:'ADDPRODUCTS'
  };
  
  export default productTypes;