const productTypes = {
    FETCHPRODUCT: 'FETCHPRODUCT',
    FETCHPRODUCTSEARCH:'FETCHPRODUCTSEARCH',
    FETCHPRODUCT_ERR: 'FETCHPRODUCT_ERR',
    ADDPRODUCTS:'ADDPRODUCTS'
  };
  
  export default productTypes;